### ISSUE TITLE
data providing

### ISSUE THREAD

**Issue by BoostMom** [andyweizhao/NLP-Capsule#3]
Hi ,

    Very nice work~
    I want to repeat your work with the same data, however little information about the data format. I am wondering would you please provide more information or data sample or link for us?

thanks very much~

**Comment by andyweizhao** [comment]
Hi BoostMom,

Thank you for your interest. You can load the dataset named eurlex_raw_text.p from google drive, which mentioned in the readme :)

**Comment by BoostMom** [comment]
my carelessness~ 😬 thanks~
