### ISSUE TITLE
Flatten模块是不是有些问题？

### ISSUE THREAD

**Issue by xyfZzz** [andyweizhao/NLP-Capsule#4]
`class FlattenCaps(nn.Module):`
    `  def __init__(self):`
        `  super(FlattenCaps, self).__init__()`
    `  def forward(self, p, a):`
        `  poses = p.view(p.size(0), p.size(2) * p.size(3) * p.size(4), -1)`
        `  activations = a.view(a.size(0), a.size(1) * a.size(2) * a.size(3), -1)`
        `  return poses, activations`
FlattenCaps模块中p的输入`p`的shape是[batch_size, 16, 32, 446, 1], 然后要把它view成[batch_size, 32 * 446 * 1, 16], 
按照pytorch的view的用法:把原先tensor中的数据按照行优先的顺序排成一个一维的数据，然后按照参数组合成其他维度的tensor：
`a=torch.Tensor([[[1,2,3],[4,5,6]]])`
`print(a.view(3,2))`
a会变成：
`tensor([[1., 2.],`
        `[3., 4.],`
        `[5., 6.]])`
也就是说，在对p进行view的时候会依次在每个长度446向量上取多个长度16的向量，然后最后变成14272个长度为16的向量，这里这样子做是不是不太对呀？

**Comment by HansiZeng** [comment]
我也有同样的疑惑。话说最后你结局了吗
