### ISSUE TITLE
textcnn那里没问题吗

### ISSUE THREAD

**Issue by HHHLLL1** [andyweizhao/NLP-Capsule#6]
卷积的轴不对吧，256个词*300向量长，ks为2，stride为2，出来不应该是最后一维不应该是128吗， 你这个出来是150

**Comment by andyweizhao** [comment]
We use a column-based instead of a row-based convolutional layer and that will convolve elements over an embedding matrix through a 256*k (not k*300) kernel filter. We adopted this column-based operation presented in XML-CNN (https://dl.acm.org/doi/10.1145/3077136.3080834) for the fair comparison.

**Comment by HHHLLL1** [comment]
thank u for the answer
