### ISSUE TITLE
how to train my own CNN_KIM model?

### ISSUE THREAD

**Issue by kaohaochuan** [andyweizhao/NLP-Capsule#8]
the model : model-EUR-CNN-40.pth
can't not use in my data

`RuntimeError: Error(s) in loading state_dict for CNN_KIM:

        size mismatch for fc1.weight: copying a param with shape torch.Size([3954, 384]) from checkpoint, the shape in current model is torch.Size([10, 384]).

        size mismatch for fc1.bias: copying a param with shape torch.Size([3954]) from checkpoint, the shape in current model is torch.Size([10]).`

my multi-label datasets number is label 9 ,EUR-Lex datasets number is 3956!
and my language is Chinese .EUR-Lex datasets language is English.
Can you help me ? Thanks a lot!

**Comment by andyweizhao** [comment]
Hi, 
The CNN_Kim model is recommended to reduce the size of the output space in the inference stage when the size of the space is large, e.g., 3900 labels. However, in the training stage, the output space is reduced to the number of labels in one batch, so the training process is efficient enough, I think. 

Concerning the language, one solution is to re-train the whole model, based on Chinese or multilingual word embeddings, or it's still legitimate to use the current pre-trained model for Chinese datasets but one needs to add an additional layer to project English embeddings into the Chinese space.

**Comment by kaohaochuan** [comment]
Thanks you !
But  I try so many days ,your code is so confusing!
I use my own word embedding and ckiptagger for tokenizer
I don't understand why you have to use baseline(CNN_KIM)to read test data to train .
Why don't just use  "Y_tst_o"
and You don't specify how to train a CNN just like  "model-EUR-CNN-40.pth"
I have tried to use my own trained capsule  network to predict 
But <class 'torch.nn.modules.module.IncompatibleKeys'>!=<class 'torch.nn.parallel.data_parallel.DataParallel'>
**capsule_net.eval()
        top_k = 50
        row_idx_list, col_idx_list, val_idx_list = [], [], []
        for batch_idx in range(nr_batches):
            start = time.time()
            start_idx = batch_idx * args.ts_batch_size
            end_idx = min((batch_idx + 1) * args.ts_batch_size, nr_tst_num)
            X = X_tst[start_idx:end_idx]
            Y = Y_tst_o[start_idx:end_idx]
            data = Variable(torch.from_numpy(X).long()).cuda()
            candidates = baseline(data)            
            candidates = candidates.data.cpu().numpy()
            Y_pred = np.zeros([candidates.shape[0], args.num_classes])
            
            for i in range(candidates.shape[0]):
                candidate_labels = candidates[i, :].argsort()[-args.re_ranking:][::-1].tolist()
                _, activations_2nd = capsule_net(data[i, :].unsqueeze(0), candidate_labels)
                Y_pred[i, candidate_labels] = activations_2nd.squeeze(2).data.cpu().numpy()
                

            for i in range(Y_pred.shape[0]):
                sorted_idx = np.argpartition(-Y_pred[i, :], top_k)[:top_k]
                row_idx_list += [i + start_idx] * top_k
                col_idx_list += (sorted_idx).tolist()
                val_idx_list += Y_pred[i, sorted_idx].tolist()
                

            done = time.time()
            elapsed = done - start

            print("\r Epoch: {} Reranking: {} Iteration: {}/{} ({:.1f}%)  Loss: {:.5f} {:.5f}".format( (epoch + 1), args.re_ranking, batch_idx, nr_batches,  batch_idx * 100 / nr_batches,0, elapsed),end="")
            # write_output = str("Epoch: {} Reranking: {} Iteration: {}/{} ({:.1f}%)  Loss: {:.5f} {:.5f}".format( (epoch + 1), args.re_ranking, batch_idx, nr_batches,  batch_idx * 100 / nr_batches,0, elapsed))
            
            # with open ("score.txt","a") as f:
            #     f.write(str(write_output))
            #     f.write("\n")

        m = max(row_idx_list) + 1
        n = max(k_trn, k_tst)
        
        Y_tst_pred = sp.csr_matrix((val_idx_list, (row_idx_list, col_idx_list)), shape=(m, n))
        

        if k_trn >= k_tst:
            Y_tst_pred = Y_tst_pred[:, :k_tst]

        evaluate(Y_tst_pred.toarray(), Y_tst)**

How to read the original test file,and just use the capsule to predict?
and why don't you use macro_F1 to score the performance?
Thanks!

**Comment by andyweizhao** [comment]
"I don't understand why you have to use baseline(CNN_KIM)to read test data to train ."
CNN_KIM is not used at train time regardless of the size of the number of labels. At test time, CNN_KIM can accelerate model predictions when the number of labels is large.

"You don't specify how to train a CNN just like "model-EUR-CNN-40.pth"
You can find the CNN-KIM model in the network.py, and it should be easy to train.

"How to read the original test file, and just use the capsule to predict?"
For a quick start, a very standard data processing script is skipped in this repo. I hope it's Ok...

"why don't you use macro_F1 to score the performance?"
This is because we tested the model on the multilabel classification tasks, where precision-K and NDCG-k are more reasonable metrics than F1.
